version: '3'
services:
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
    - 11311:11211
    networks:
      - internal

  balancer:
    image: nginx:latest
    container_name: nginx-balancer
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/core:/etc/nginx/conf.d
      - ./../src:/var/www/
      - ./nginx/Logs:/var/log/nginx/
      - ./nginx/html:/usr/share/nginx/html/
    depends_on:
      - php
      - nginx1
      - nginx2
    networks:
      - internal

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - 8081:8081
      - 4431:4431
    volumes:
      - ./nginx1/core:/etc/nginx/conf.d
      - ./../src:/var/www/
      - ./nginx1/Logs:/var/log/nginx/
      - ./nginx1/html:/usr/share/nginx/html/
    depends_on:
      - php
    networks:
      - internal

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - 8082:8082
      - 4432:4432
    volumes:
      - ./nginx2/core:/etc/nginx/conf.d
      - ./../src:/var/www/
      - ./nginx2/Logs:/var/log/nginx/
      - ./nginx2/html:/usr/share/nginx/html/
    depends_on:
      - php
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: preorder
      MYSQL_USER: preorderuser
      MYSQL_PASSWORD: preorderuser


    volumes:
      - ./MySQL:/var/lib/mysql
    networks:
        - internal

  php:
    container_name: php-fpm
    build:
      context: ./PHP
      args:
        - USER_ID
        - GROUP_ID

    volumes:
      - ./../src:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
      - memcached
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28