version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/core:/etc/nginx/conf.d
      - ./../src:/var/www/
      - ./nginx/Logs:/var/log/nginx/
      - ./nginx/html:/usr/share/nginx/html/
    depends_on:
      - php
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
  
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: preorder
      MYSQL_USER: preorderuser
      MYSQL_PASSWORD: preorderuser


    volumes:
      - ./MySQL:/var/lib/mysql
    networks:
        - internal

  php:
    container_name: php-fpm
    build:
      context: ./PHP
      args:
        - USER_ID
        - GROUP_ID

    volumes:
      - ./../src:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28